const path = require('path');

// Export version info to a file
const fs = require('fs');
fs.writeFileSync(path.resolve(path.join(__dirname, 'src/version.ts')),
`// This file is auto-generated by the build system.
import * as pkg from '../package.json';
export const BundleVersion = pkg.name + '-' + pkg.version;
`);

module.exports = {
    entry: {
        bundle: './src/index.ts',
        logFileWorker: './assets/jsutils/logFileWorker.js',
        channelsIndexedDbWorker: './assets/jsutils/channelsIndexedDbWorker.js',
        dmIndexedDbWorker: './assets/jsutils/dmIndexedDbWorker.js',
        ndf: './assets/jsutils/ndf.js',
        stateIndexedDbWorker: './assets/jsutils/stateIndexedDbWorker.js',
        wasm_exec: './wasm_exec.js',
    },
    devtool: 'inline-source-map',
    mode: 'development',
    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'dist'),
        globalObject: 'this',
        library: {
            name: 'xxdk',
            type: 'umd',
        },
        umdNamedDefine: true,
        publicPath: '/dist/',
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                use: 'ts-loader',
                exclude: /node_modules/,
            },
            {
                test: /\.wasm$/,
                type: 'asset/resource',
                generator: {
                    filename: 'assets/wasm/[hash][ext][query]'
                }
            }
        ]
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js' ],
    }
};
